// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package film_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilmServiceClient is the client API for FilmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilmServiceClient interface {
	ListFilmsV1(ctx context.Context, in *ListFilmsV1Request, opts ...grpc.CallOption) (*ListFilmsV1Response, error)
	DescribeFilmV1(ctx context.Context, in *DescribeFilmV1Request, opts ...grpc.CallOption) (*DescribeFilmV1Response, error)
	CreateFilmV1(ctx context.Context, in *CreateFilmV1Request, opts ...grpc.CallOption) (*CreateFilmV1Response, error)
	RemoveFilmV1(ctx context.Context, in *RemoveFilmV1Request, opts ...grpc.CallOption) (*RemoveFilmV1Response, error)
}

type filmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilmServiceClient(cc grpc.ClientConnInterface) FilmServiceClient {
	return &filmServiceClient{cc}
}

func (c *filmServiceClient) ListFilmsV1(ctx context.Context, in *ListFilmsV1Request, opts ...grpc.CallOption) (*ListFilmsV1Response, error) {
	out := new(ListFilmsV1Response)
	err := c.cc.Invoke(ctx, "/alex1472.ozon_film_service.film_service.v1.FilmService/ListFilmsV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) DescribeFilmV1(ctx context.Context, in *DescribeFilmV1Request, opts ...grpc.CallOption) (*DescribeFilmV1Response, error) {
	out := new(DescribeFilmV1Response)
	err := c.cc.Invoke(ctx, "/alex1472.ozon_film_service.film_service.v1.FilmService/DescribeFilmV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) CreateFilmV1(ctx context.Context, in *CreateFilmV1Request, opts ...grpc.CallOption) (*CreateFilmV1Response, error) {
	out := new(CreateFilmV1Response)
	err := c.cc.Invoke(ctx, "/alex1472.ozon_film_service.film_service.v1.FilmService/CreateFilmV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) RemoveFilmV1(ctx context.Context, in *RemoveFilmV1Request, opts ...grpc.CallOption) (*RemoveFilmV1Response, error) {
	out := new(RemoveFilmV1Response)
	err := c.cc.Invoke(ctx, "/alex1472.ozon_film_service.film_service.v1.FilmService/RemoveFilmV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilmServiceServer is the server API for FilmService service.
// All implementations must embed UnimplementedFilmServiceServer
// for forward compatibility
type FilmServiceServer interface {
	ListFilmsV1(context.Context, *ListFilmsV1Request) (*ListFilmsV1Response, error)
	DescribeFilmV1(context.Context, *DescribeFilmV1Request) (*DescribeFilmV1Response, error)
	CreateFilmV1(context.Context, *CreateFilmV1Request) (*CreateFilmV1Response, error)
	RemoveFilmV1(context.Context, *RemoveFilmV1Request) (*RemoveFilmV1Response, error)
	mustEmbedUnimplementedFilmServiceServer()
}

// UnimplementedFilmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilmServiceServer struct {
}

func (UnimplementedFilmServiceServer) ListFilmsV1(context.Context, *ListFilmsV1Request) (*ListFilmsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFilmsV1 not implemented")
}
func (UnimplementedFilmServiceServer) DescribeFilmV1(context.Context, *DescribeFilmV1Request) (*DescribeFilmV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeFilmV1 not implemented")
}
func (UnimplementedFilmServiceServer) CreateFilmV1(context.Context, *CreateFilmV1Request) (*CreateFilmV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFilmV1 not implemented")
}
func (UnimplementedFilmServiceServer) RemoveFilmV1(context.Context, *RemoveFilmV1Request) (*RemoveFilmV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFilmV1 not implemented")
}
func (UnimplementedFilmServiceServer) mustEmbedUnimplementedFilmServiceServer() {}

// UnsafeFilmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilmServiceServer will
// result in compilation errors.
type UnsafeFilmServiceServer interface {
	mustEmbedUnimplementedFilmServiceServer()
}

func RegisterFilmServiceServer(s grpc.ServiceRegistrar, srv FilmServiceServer) {
	s.RegisterService(&FilmService_ServiceDesc, srv)
}

func _FilmService_ListFilmsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilmsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).ListFilmsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alex1472.ozon_film_service.film_service.v1.FilmService/ListFilmsV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).ListFilmsV1(ctx, req.(*ListFilmsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_DescribeFilmV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeFilmV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).DescribeFilmV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alex1472.ozon_film_service.film_service.v1.FilmService/DescribeFilmV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).DescribeFilmV1(ctx, req.(*DescribeFilmV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_CreateFilmV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilmV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).CreateFilmV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alex1472.ozon_film_service.film_service.v1.FilmService/CreateFilmV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).CreateFilmV1(ctx, req.(*CreateFilmV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_RemoveFilmV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFilmV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).RemoveFilmV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alex1472.ozon_film_service.film_service.v1.FilmService/RemoveFilmV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).RemoveFilmV1(ctx, req.(*RemoveFilmV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FilmService_ServiceDesc is the grpc.ServiceDesc for FilmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alex1472.ozon_film_service.film_service.v1.FilmService",
	HandlerType: (*FilmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFilmsV1",
			Handler:    _FilmService_ListFilmsV1_Handler,
		},
		{
			MethodName: "DescribeFilmV1",
			Handler:    _FilmService_DescribeFilmV1_Handler,
		},
		{
			MethodName: "CreateFilmV1",
			Handler:    _FilmService_CreateFilmV1_Handler,
		},
		{
			MethodName: "RemoveFilmV1",
			Handler:    _FilmService_RemoveFilmV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alex1472/film_service_api/v1/film_service_api.proto",
}
